### ISSUE TITLE
Can't enter multiple OZ's

### ISSUE THREAD

**Issue by joshuadelange** [4kmapping/4kadopt_server#5]
Get the error (1062, "Duplicate entry 'NLD-LIM' for key 'worldid'") when testing with multiple OZ's on the initial load. Need to have this so I can make sure the earliest target year always shows.

**Comment by coolkang** [comment]
First off, please make sure if you don't already have the world id under the user account you are using for testing. The combination of target year and user account should be unique in db because we don't allow the same user adopt a same OZ multiple times.

If the above is not the case, please tell me more on how to reproduce the issue.
